'use client';

import { useState } from 'react';

export default function ScreenshotViewer({ results, campaign, onEdit }) {
  const [selected, setSelected] = useState(0);

  if (!results || !results.results) return null;

  const completedResults = results.results.filter(r => r.status === 'completed' && r.screenshotPath);

  if (completedResults.length === 0) {
    return (
      <div className="text-center py-12 text-gray-400">
        <div className="text-4xl mb-3">📷</div>
        <div>No screenshots were generated. Check the match report above for details.</div>
      </div>
    );
  }

  const current = completedResults[selected];

  return (
    <div>
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-2xl font-bold text-[#1A1A2E]">Screenshots</h2>
        <div className="flex gap-2">
          {onEdit && (
            <button
              onClick={() => onEdit(current)}
              className="px-4 py-2 bg-gray-100 text-gray-700 rounded-lg text-sm font-medium hover:bg-gray-200 transition-colors flex items-center gap-2"
            >
              <span>✏️</span> Edit Mockup
            </button>
          )}
          <a
            href={`/api/screenshot?path=${encodeURIComponent(current.screenshotPath)}`}
            download
            className="px-4 py-2 bg-[#00B4D8] text-white rounded-lg text-sm font-medium hover:bg-[#00B4D8]/90 transition-colors flex items-center gap-2"
          >
            <span>⬇️</span> Download PNG
          </a>
        </div>
      </div>

      {/* Tab selector for multiple URLs */}
      {completedResults.length > 1 && (
        <div className="flex gap-2 mb-4 overflow-x-auto pb-2">
          {completedResults.map((r, i) => (
            <button
              key={r.mockupId}
              onClick={() => setSelected(i)}
              className={`px-4 py-2 rounded-lg text-sm font-medium whitespace-nowrap transition-all ${
                i === selected
                  ? 'bg-[#1A1A2E] text-white'
                  : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
              }`}
            >
              {r.domain}
            </button>
          ))}
        </div>
      )}

      {/* Screenshot display */}
      <div className="bg-white rounded-xl border border-gray-200 overflow-hidden shadow-sm">
        <div className="bg-gray-50 px-4 py-2 border-b border-gray-200 flex items-center gap-3">
          <div className="flex gap-1.5">
            <div className="w-3 h-3 rounded-full bg-red-400" />
            <div className="w-3 h-3 rounded-full bg-yellow-400" />
            <div className="w-3 h-3 rounded-full bg-green-400" />
          </div>
          <span className="text-xs text-gray-400 truncate flex-1">{current.url}</span>
          <span className="text-xs text-gray-300">
            {current.matchReport?.totalMatched || 0} creative(s) injected
          </span>
        </div>

        <div className="max-h-[700px] overflow-y-auto">
          <img
            src={`/api/screenshot?path=${encodeURIComponent(current.screenshotPath)}`}
            alt={`Mockup for ${current.domain}`}
            className="w-full"
          />
        </div>
      </div>

      {/* Metadata footer */}
      <div className="mt-3 flex items-center justify-between text-xs text-gray-400">
        <span>
          {campaign.client_name} / {campaign.name} — {current.domain}
        </span>
        <span>
          {new Date().toLocaleDateString()} — Generated by AdVision
        </span>
      </div>
    </div>
  );
}
